### ISSUE TITLE
Sample code is not working

### ISSUE THREAD

**Issue by oom-** [romainsimon/neuroevolution#5]
```error
TypeError: genome.generateNetwork is not a function
    at population.evolve.genome (\NEAT\index.js:11:26)
    at Chromosome.calculateFitness (\NEAT\node_modules\neuroevolution\src\chromosome.class.js:34:20)
    at Population.evaluate (\NEAT\node_modules\neuroevolution\src\population.class.js:36:18)
    at Population.evolve (\node_modules\neuroevolution\src\population.class.js:98:12)
    at Object.<anonymous> (\NEAT\index.js:10:12)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by wongjiahau** [comment]
I hit this error too :(

**Comment by brunnolou** [comment]
It looks like this Repo it's not in sync with `npm`.
@romainsimon could you please update the npm?


![image](https://user-images.githubusercontent.com/2729225/94992147-dfe14500-057f-11eb-92ec-ad03d6ba1f81.png)
https://npm.runkit.com/neuroevolution/index.js?t=1601729106722
